name: 'YAML Schema Validator'
description: 'Validate YAML files in a repo according to settings'
branding:
  icon: 'award'
  color: 'green'
inputs:
  settingsFile:
    description: 'Location of schema configuration file'
    required: false
    default: '.vscode/settings.json'
  yamlSchemasJson:
    description: 'The yaml.schemas config as inline JSON'
    required: false
outputs:
  validFiles:
    description: 'Comma separated list of files that passed the schema validation'
  invalidFiles:
    description: 'Comma separated list of files that failed the schema validation'
runs:
  using: 'node12'
  main: 'lib/index.js'
branding:
  icon: 'check'
  color: orange
